# Generated by Django 2.2.1 on 2019-07-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_req', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('fastpass', models.CharField(max_length=200)),
                ('park', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
    ]
