# Generated by Django 2.2.1 on 2019-07-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attraction_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
